# Generated by Django 2.2 on 2020-03-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(default='000', max_length=10)),
                ('description', models.CharField(default='', max_length=200)),
                ('level', models.CharField(default='', max_length=10)),
                ('semester', models.CharField(default='', max_length=10)),
                ('teacher', models.CharField(blank=True, max_length=10)),
                ('lecture_hour', models.IntegerField(default=1)),
                ('tp_hour', models.IntegerField(default=1)),
                ('status', models.CharField(default='CLOSE', max_length=10)),
                ('create_by', models.CharField(default='', max_length=100)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
